### ISSUE TITLE
Game crashes when clicking on mod in forges mod viewer

### ISSUE THREAD

**Issue by SonicCraft** [ScottCTD/ScottsEssential#3] opened 2021-01-27 23:02 UTC
I was configuring mods for a modpack I'm working on currently and when I clicked on your mod to open the config my minecraft instance displayed the "Saving World" screen even though I was on the main menu and closed. I relaunched the game and clicking on it made minecraft do the same thing again. I have included my crashlog

[crash-2021-01-27_17.56.52-client.txt](https://github.com/ScottCTD/ScottsEssential/files/5883654/crash-2021-01-27_17.56.52-client.txt)

**Comment by scottctd** [comment] 2021-01-28 03:15
I'm sorry that I could not reproduce what you encountered. I opened this screen and no crash happened: 
![image](https://user-images.githubusercontent.com/35100768/106084278-03488500-6159-11eb-8cb9-09a7a2f210d9.png)

And I don't know how to open the configuration file on this screen because the config button is not available.
By the way, the config file of my mod is in the "serverconfig" folder in every world you have. If you want to let a default config apply to every world you have, you could copy the config file in the "serverconfig" folder you want to ".minecraft/defaultconfigs" folder.

Thanks for your time, Good day!
I'm happy to hear your any further information, thanks!

**Comment by scottctd** [comment] 2021-08-03 08:37
It's been a long time..., close it

**Closed as completed by scottctd** 2021-08-03 08:37 UTC
Labels: bug, need further info
